# Node.js
# Build a general Node.js project with npm.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

trigger:
  branches:
    include:
    - main
  paths:
    exclude:
    - README.md
pr: none 

pool:
  vmImage: ubuntu-latest

steps:
- task: NodeTool@0
  inputs:
    versionSpec: '18.x'
  displayName: 'Install Node.js'

- script: |
    npm install
  displayName: 'npm install'

- script: |
    npm run build
  displayName: 'npm run build'

- script: |
    npm run test:ci
  displayName: 'npm run test'

- task: Docker@2
  displayName: 'Build and push Docker image'
  inputs:
    containerRegistry: 'BeedataApp'
    repository: 'appbeetdigital'
    command: 'buildAndPush'
    Dockerfile: 'Dockerfile'
    tags: '1.0.$(Build.BuildId)'
- task: AzureContainerApps@1
  inputs:
    azureSubscription: 'Bee_Prototipos(ad415fa8-3333-44cc-8337-4001938578c8)'
    acrName: 'appbeetdigital'
    acrUsername: $(ACR-USER)
    acrPassword: $(ACR-PWD)
    imageToDeploy: 'appbeetdigital.azurecr.io/appbeetdigital:1.0.$(Build.BuildId)'
    containerAppName: 'app'
    resourceGroup: 'appbeetdigital'
    containerAppEnvironment: 'appbeetdigital'
    targetPort: '3000'
    location: 'East US'
    disableTelemetry: true